# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-09-04 02:10
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sgc', '0002_auto_20170903_1330'),
    ]

    operations = [
        migrations.CreateModel(
            name='social_auth_usersocialauth',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=20)),
                ('contrasena', models.CharField(max_length=20)),
            ],
        ),
    ]
